"""
scripts/generate_b2_parity_report.py — Produces the B2-vs-published
comparison artifact for A14's blocking gate (tests/test_b2_rcaeval_parity.py).

This exists because the parity test itself only asserts pass/fail inline;
it does not leave a durable, inspectable side-by-side table anywhere in
the repo. Run this once against the real RE2-TT dataset to regenerate
docs/b2_rcaeval_parity_report.md/.csv, which IS committed and can be
read without re-running the 2.8GB-dataset test.

Usage:
    python scripts/generate_b2_parity_report.py --re2tt-dir /path/to/RE2-TT
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))

PUBLISHED_AVG_AT_5 = {
    "cpu": 0.72,
    "memory": 0.99,
    "disk": 1.0,
    "socket": 0.83,
    "delay": 0.63,
    "loss": 0.64,
}

FAULT_LABELS = {
    "cpu": "CPU",
    "memory": "MEM",
    "disk": "DISK",
    "socket": "SOCKET",
    "delay": "DELAY",
    "loss": "LOSS",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--re2tt-dir", required=True, type=Path)
    parser.add_argument(
        "--out-md", type=Path, default=REPO_ROOT / "docs" / "b2_rcaeval_parity_report.md"
    )
    parser.add_argument(
        "--out-csv", type=Path, default=REPO_ROOT / "docs" / "b2_rcaeval_parity_report.csv"
    )
    args = parser.parse_args()

    from bench.baselines.rcaeval_baseline import rank as b2_rank
    from bench.metrics import average_at_k
    from pre.signals.rcaeval import RCAEvalAdapter

    root = args.re2tt_dir.parent
    adapter = RCAEvalAdapter(root, "RE2-TT")
    cases = list(adapter)
    if len(cases) != 90:
        print(f"WARNING: expected 90 RE2-TT cases, got {len(cases)}", file=sys.stderr)

    per_fault: dict[str, list] = {ft: [] for ft in PUBLISHED_AVG_AT_5}
    for case, gt in cases:
        ranks = b2_rank(case, inject_time=gt.inject_time)
        per_fault[gt.fault_type].append((ranks, gt.root_cause_service))

    rows = []
    for fault_type, published in PUBLISHED_AVG_AT_5.items():
        ranked_answers = per_fault[fault_type]
        observed_raw = average_at_k(ranked_answers, k=5) if ranked_answers else None
        # RCAEval's own main.py prints round(evaluator.average(5), 2) --
        # the README table is already rounded to 2dp, so compare rounded
        # to rounded. Comparing raw-vs-rounded produces a spurious diff of
        # up to 1/300 whenever the true fraction k/75 has k % 3 != 0 (see
        # docs/b2_rcaeval_parity_report.md for the worked explanation).
        observed = round(observed_raw, 2) if observed_raw is not None else None
        diff = None if observed is None else round(observed - published, 4)
        rows.append(
            {
                "fault_type": FAULT_LABELS[fault_type],
                "n_cases": len(ranked_answers),
                "published_avg_at_5": published,
                "observed_avg_at_5_raw": round(observed_raw, 4) if observed_raw is not None else None,
                "observed_avg_at_5_rounded": observed,
                "diff": diff,
                "exact_match_after_rounding": (diff is not None and diff == 0.0),
            }
        )

    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    with args.out_csv.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    lines = [
        "# B2 (RCAEval BARO) vs. published RCAEval README table — RE2-TT",
        "",
        "Generated by `scripts/generate_b2_parity_report.py` against the real,",
        "checksum-verified RE2-TT dataset (Zenodo record 14590730), run through",
        "`pre.signals.rcaeval.RCAEvalAdapter` and `bench.baselines.rcaeval_baseline`",
        "— i.e. through our own adapter/harness code path, not RCAEval's raw CSV loader.",
        "",
        "Published numbers are from the RCAEval README",
        "(`python main.py --method baro --dataset re2-tt --length 20`), which itself",
        "prints `round(evaluator.average(5), 2)` — already rounded to 2 decimal",
        "places, not the raw float. `observed_avg_at_5_rounded` below is rounded the",
        "same way before comparing, so the diff reflects a genuine scoring",
        "discrepancy rather than raw-vs-rounded rounding noise (see `observed_avg_at_5_raw`",
        "for the unrounded value, and https://github.com/phamquiluan/RCAEval/blob/main/main.py",
        "for the print statement this reproduces).",
        "",
        "| Fault | N cases | Published Avg@5 | Observed (raw) | Observed (rounded) | Diff | Exact match to published rounded values |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['fault_type']} | {row['n_cases']} | {row['published_avg_at_5']} | "
            f"{row['observed_avg_at_5_raw']} | {row['observed_avg_at_5_rounded']} | "
            f"{row['diff']:+.4f} | "
            f"{'✅' if row['exact_match_after_rounding'] else '❌'} |"
        )

    all_pass = all(r["exact_match_after_rounding"] for r in rows)
    lines.append("")
    lines.append(f"**Overall: {'PASS' if all_pass else 'FAIL'}**")

    args.out_md.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {args.out_md} and {args.out_csv}")
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
